CREATE TABLE [dbo].[TB_LG_TIPO_USUARIO](
	[ID_TIPO_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[DS_TIPO_USUARIO] [varchar](50) NULL,
 CONSTRAINT [PK_TB_LG_TIPO_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [TB_LG_USUARIO] 
WITH CHECK ADD CONSTRAINT [FK_TB_LG_TIPO_USUARIO]
FOREIGN KEY ([ID_TIPO_USUARIO])
REFERENCES [TB_LG_TIPO_USUARIO] ([ID_TIPO_USUARIO])