CREATE TABLE [dbo].[TB_LG_GAME](
	[ID_GAME] [int] IDENTITY(1,1) NOT NULL,
	[DS_GAME] [varchar](255) NULL,
	[VL_TEMPO] [INT] NULL,
	[FLG_POSSUI_ONLINE] [BIT] NULL,
	[ID_STATUS_GAME] [INT] NULL,
	[VL_ANO_CONCLUIDO] [INT] NULL,
 CONSTRAINT [PK_TB_LG_GAME] PRIMARY KEY CLUSTERED 
(
	[ID_GAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
