CREATE TABLE [dbo].[TB_LG_USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[DS_LOGIN] [varchar](18) NULL,
	[DS_SENHA] [varchar](50) NULL,
 CONSTRAINT [PK_TB_LG_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE TB_LG_USUARIO ADD DT_CRIACAO DATETIME NULL
ALTER TABLE TB_LG_USUARIO ADD DT_ALTERACAO DATETIME NULL
ALTER TABLE TB_LG_USUARIO ADD ST_FLG_ATIVO BIT NULL
ALTER TABLE TB_LG_USUARIO ADD DS_EMAIL VARCHAR(255) NULL
ALTER TABLE TB_LG_USUARIO ADD ID_TIPO_USUARIO INT NULL
