CREATE TABLE [dbo].[TB_LG_STATUS_GAME](
	[ID_STATUS_GAME] [int] IDENTITY(1,1) NOT NULL,
	[DS_STATUS_GAME] [varchar](50) NULL,
 CONSTRAINT [PK_TB_LG_STATUS_GAME] PRIMARY KEY CLUSTERED 
(
	[ID_STATUS_GAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [TB_LG_GAME] 
WITH CHECK ADD CONSTRAINT [FK_TB_LG_STATUS_GAME]
FOREIGN KEY ([ID_STATUS_GAME])
REFERENCES [TB_LG_STATUS_GAME] ([ID_STATUS_GAME])